#!/usr/bin/env bash
# Creates a file containig its own PID
# Displays a string indefinitly

trap 'echo "I hate the kill command";rm /var/run/myscript.pid; exit 0' SIGTERM
trap 'echo "Y no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid; exit 0' SIGQUIT or SIGQUIT
echo $$ > /var/run/myscript.pid
while :
do
	echo "To infinity and beyond"
	sleep 2
done

