#!/usr/bin/env bash
# init script that manages my_process
pid_file="/var/run/my_process.pid"
start() {
	./manage_my_process &
	echo $!>$pid_file
	echo "manage_my_process started"

}
stop() {
	kill "$(cat $pid_file)"
	rm $pid_file
	echo "manage_my_process stopped"
}
restart() {
	kill "$(cat $pid_file)"
	rm $pid_file
	./manage_my_process &
	echo $!>$pid_file
	echo "manage_my_process restarted"
}
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
esac
