#!/usr/bin/env bash
#Displays to infinity and beyond indefinitely
# Display I am invincible!!! when receiving SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM
while :
do
	echo "To infinity and beyond"
	sleep 2
done
