#!/usr/bin/env bash
#Resolve localhost to 127.0.0.2
#resolve facebook.com to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.cpy
cp -f ~/hosts.new /etc/hosts

